name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install -v

    - name: Rebuild virtual environment
      run: |
        deactivate || true
        rm -rf .venv
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        poetry install -v

    - name: Lint example directory
      run: |
        source .venv/bin/activate
        poetry run flake8 example/

    - name: Lint tests directory
      run: |
        source .venv/bin/activate
        poetry run flake8 tests/

    - name: Check code formatting
      run: |
        source .venv/bin/activate
        poetry run black --check .

    - name: Run tests
      run: |
        source .venv/bin/activate
        poetry run pytest
      env:
        PYTHONPATH: .venv/lib/python${{ matrix.python-version }}/site-packages
